"""empty message

Revision ID: 40520ce238aa
Revises: 6487fcdc80b9
Create Date: 2024-07-19 23:58:02.418760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40520ce238aa'
down_revision = '6487fcdc80b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=80), nullable=False))
        batch_op.drop_column('birth_years')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_years', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
