"""empty message

Revision ID: eb40437b0bf2
Revises: 40520ce238aa
Create Date: 2024-07-20 00:05:56.929327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb40437b0bf2'
down_revision = '40520ce238aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.String(length=120), nullable=True))
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.drop_column('gener')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=True))
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('population')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gener', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('homeworld')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
